name: Deploy to Vercel
on: [push, pull_request]
jobs:

  setup: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: install deps
        run: yarn install

      - name: run lint Test
        run: yarn run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: yarn build
        env:
          DISABLE_ESLINT_PLUGIN: true 
          CI: false

  deploy-staging: 
    runs-on: ubuntu-latest
    steps:
      - name: deploy staging 
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./build

  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to production 
        uses: amondnet/vercel-action@v25
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          vercel-args: '--prod' 
          vercel-org-id: ${{ secrets.ORG_ID}} 
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./build